### ISSUE TITLE
Small typo in blog post

### ISSUE THREAD

**Issue by domspad** [AllenDowney/ProbablyOverthinkingIt#1]
I noticed a small typo in [one](http://allendowney.blogspot.com/2014/09/two-hour-marathon-in-2041.html) of your blog posts! 

The last paragraph: 

> The red line is the target: 13.1 mph [≈ World record time marathon, 2h03m59s].  The blue line is a least squares fit to the data.  So here's my prediction: there will be a 2-hour marathon in 2043.  I'll be 76, so my chances of seeing it are pretty good.  But that's a topic for another article (see Chapter 1 of Think Bayes).

says "2043" where it should be "2041"

Really enjoyed the series!

**Comment by AllenDowney** [comment]
Fixed.  Thanks!
